FROM openjdk:8u141-jdk
MAINTAINER chris.stefani@outlook.com

WORKDIR /app
ENV ROOT="/app"

COPY atd_example/build.gradle atd_example/gradlew /app/
COPY atd_example/gradle/ /app/gradle/
COPY /atd_example/ $ROOT/

RUN ./gradlew compileTestJava clean \
    && rm -rf  src/
